[buildPlans.Monocode]
family = "Monocode"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

[buildPlans.Monocode.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-j = "flat-hook-serifed"
capital-q = "crossing"
capital-w = "straight-flat-top-serifless"
f = "flat-hook-serifless-crossbar-at-x-height"
i = "hooky"
j = "flat-hook-serifed"
k = "symmetric-connected-serifless"
l = "serifed-semi-tailed"
t = "flat-hook-short-neck"
w = "straight-flat-top-serifless"
zero = "dotted"
two = "straight-neck-serifless"
three = "flat-top-serifless"
five = "oblique-arched-serifless"
punctuation-dot = "square"
asterisk = "penta-mid"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "upper-open"
question = "corner-flat-hooked"

[buildPlans.Monocode.variants.italic]
e = "flat-crossbar"
f = "flat-hook-extended-crossbar-at-x-height"
i = "serifed-semi-tailed"
k = "symmetric-connected-serifless"
l = "serifed-semi-tailed"
y = "straight-serifless"

[buildPlans.Monocode.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.Monocode.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Monocode.weights.Medium]
shape = 500
menu = 500
css = 500

[buildPlans.Monocode.weights.SemiBold]
shape = 600
menu = 600
css = 600

[buildPlans.Monocode.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Monocode.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.Monocode.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Monocode.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.Monocode.metricOverride]
ascender = 750
xHeight = 540
