[buildPlans.monocode]
family = "Monocode"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

  [buildPlans.monocode.variants]
  inherits = "ss14"

    [buildPlans.monocode.variants.design]
    g = "double-storey-open"
    i = "hooky"
    k = "straight-serifless"
    l = "serifed"
    r = "serifless"
    y = "straight-turn"
    one = "no-base"
    four = "semi-open"
    seven = "bend-serifless"
    brace = "curly-flat-boundary"
    at = "fourfold"
    dollar = "interrupted"
    percent = "rings-segmented-slash"
    punctuation-dot = "square"

    [buildPlans.monocode.variants.italic]
    a = "single-storey-tailed"
    f = "flat-hook-extended"
    i = "tailed-serifed"
    l = "tailed-serifed"

[buildPlans.monocode.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.monocode.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.monocode.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.monocode.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.monocode.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.monocode.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.monocode.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.monocode.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.monocode.metric-override]
xHeight = 550
leading = 1250
