name: Create Images

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up ImageMagick
        run: |
          sudo apt-get install imagemagick
          export PATH=$PATH:/usr/bin:/usr/local/bin:/usr/local/imagemagick/bin

      - name: Download Monocode
        id: download_monocode
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: merge.yml
          workflow_conclusion: success
          name: build-output
          path: /home/runner/work/monocode/fonts

      - name: Install font
        run: |
          cd /home/runner/work/monocode/fonts/ttf
          sudo cp ./*.ttf /usr/local/share/fonts
          sudo fc-cache -f -v

      - name: Generate header image
        run: |
          mkdir -p /home/runner/work/monocode/images
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' -gravity center -font Monocode-Semibold -pointsize 144 -fill '#c0caf5' \
          -draw "text 0,-150 'Monocode'" \
          -gravity center \
          -font Monocode-Light-Italic -pointsize 72 -fill '#73daca' \
          -draw "text 0,0 'printf(\"hello, world\")'" \
          -gravity center \
          -font Monocode-Medium -pointsize 86 -fill '#7dcfff' \
          -annotate +0+150 "A font for [{code}]" \
          monocode.png

          cp ./monocode.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode.png

      - name: Generate specimen image
        run: |
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' -gravity north -font Monocode -pointsize 256 -fill '#c0caf5' \
          -draw "text 0,10 'Aa'" \
          -gravity center \
          -font Monocode -pointsize 60 -fill '#c0caf5' \
          -draw "text 0,40 'ABCDEFGHIJKLMNOPQRSTUVWXYZ 01234'" \
          -gravity center \
          -font Monocode -pointsize 60 -fill '#c0caf5' \
          -draw "text 0,120 'abcdefghijklmnopqrstuvwxyz 56789'" \
          -gravity center \
          -font Monocode -pointsize 60 -fill '#c0caf5' \
          -draw "text 0,210 '{}[]()<>\`~!@#$%^&*?,.;:\'\"-_+=|\/'" \
          monocode-specimen.png

          cp ./monocode-specimen.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode-specimen.png

      - name: Generate weights image
        run: |
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' \
          -gravity north -font Monocode-Light -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,20 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Light-Italic -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,80 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,140 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Italic -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,200 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Medium -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,260 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Medium-Italic -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,320 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Semibold -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,380 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Semibold-Italic -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,440 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Bold -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,500 'A quick brown fox jumps over the lazy dog'" \
          -gravity north -font Monocode-Bold-Italic -pointsize 45 -fill '#c0caf5' \
          -draw "text 0,560 'A quick brown fox jumps over the lazy dog'" \
          monocode-weights.png

          cp ./monocode-weights.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode-weights.png

      - name: Generate powerline image
        run: |
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' \
          -gravity north -font Monocode -pointsize 80 -fill '#c0caf5' \
          -draw "text 0,75 '     '" \
          -gravity center -font Monocode -pointsize 80 -fill '#c0caf5' \
          -draw "text 0,0 '       '" \
          -gravity south -font Monocode -pointsize 80 -fill '#c0caf5' \
          -draw "text 0,75 '       '" \
          monocode-powerline.png

          cp ./monocode-powerline.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode-powerline.png

      - name: Generate distinct image
        run: |
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' \
          -gravity north -font Monocode -pointsize 160 -fill '#c0caf5' \
          -draw "text 0,25 '0O  Il  1l'" \
          -gravity center -font Monocode -pointsize 160 -fill '#c0caf5' \
          -draw "text 0,0 'Z2  B8  71'" \
          -gravity south -font Monocode -pointsize 160 -fill '#c0caf5' \
          -draw "text 0,25 '6G  ;:  S5'" \
          monocode-distinct.png

          cp ./monocode-distinct.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode-distinct.png

      - name: Commit and push image changes
        run: |
          cd /home/runner/work/monocode/monocode
          git config --local user.email "aaronmbos@gmail.com"
          git config --local user.name "Aaron Bos"

          status=$(git status --porcelain)

          if [[ -z "$status" ]]; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Update images"
            git push
          fi
