name: Create Images

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up ImageMagick
        run: sudo apt-get install imagemagick

      - name: Download Monocode
        id: download_monocode
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: merge.yml
          workflow_conclusion: success
          name: build-output
          path: /home/runner/work/monocode/fonts

      - name: Unzip output
        run: |
          cd /home/runner/work/monocode/fonts
          unzip -o build-output.zip

      - name: Install font
        run: |
          cd /home/runner/work/monocode/fonts/ttf
          sudo cp ./*.ttf /usr/local/share/fonts
          sudo fc-cache -f -v

      - name: Generate header image
        run: |
