name: Create Images

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up ImageMagick
        run: |
          sudo apt-get install imagemagick
          export PATH=$PATH:/usr/bin:/usr/local/bin:/usr/local/imagemagick/bin

      - name: Download Monocode
        id: download_monocode
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: merge.yml
          workflow_conclusion: success
          name: build-output
          path: /home/runner/work/monocode/fonts

      - name: Install font
        run: |
          cd /home/runner/work/monocode/fonts/ttf
          sudo cp ./*.ttf /usr/local/share/fonts
          sudo fc-cache -f -v

      - name: Generate header image
        run: |
          mkdir -p /home/runner/work/monocode/images
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#' -gravity center \
          -font monocode -pointsize 144 -annotate 0 \
          "<<<tspan font-weight='light' fill='#c0caf5'>Mo</tspan><tspan font-weight='regular' fill='#c0caf5'>no</tspan><tspan font-weight='semi-bold' font-style='normal' fill='#c0caf5'>co</tspan><tspan font-weight='bold' fill='#c0caf5'>de</tspan>>>" \
          monocode.jpg

          cp ./monocode.jpg /home/runner/work/monocode/monocode/images
          git add /home/runner/work/monocode/monocode/images/monocode.jpg

      - name: Commit and push images
        run: |
          cd /home/runner/work/monocode/monocode
          git config --local user.email "aaronmbos@gmail.com"
          git config --local user.name "Aaron Bos"

          git commmit -m "Update images"
          git push
