name: Create Images

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  workflow_call:

env:
  NODE_VERSION: "16.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up ImageMagick
        run: |
          sudo apt-get install imagemagick
          export PATH=$PATH:/usr/bin:/usr/local/bin:/usr/local/imagemagick/bin

      - name: Download Monocode
        id: download_monocode
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: merge.yml
          workflow_conclusion: success
          name: build-output
          path: /home/runner/work/monocode/fonts

      - name: Install font
        run: |
          cd /home/runner/work/monocode/fonts/ttf
          sudo cp ./*.ttf /usr/local/share/fonts
          sudo fc-cache -f -v

      - name: Generate header image
        run: |
          mkdir -p /home/runner/work/monocode/images
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' -gravity center -font Monocode-Semibold -pointsize 144 -fill '#c0caf5' \
          -draw "text 0,-150 'Monocode'" \
          -gravity center \
          -font Monocode -pointsize 72 -fill '#c0caf5' \
          -draw "text 0,0 'printf(\"hello, world\")'" \
          -gravity center \
          -font Monocode -pointsize 86 -fill '#c0caf5' \
          -annotate +0+150 "A font for [{code}]" \
          monocode.png

          cp ./monocode.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode.png

      - name: Generate specimen image
        run: |
          cd /home/runner/work/monocode/images
          convert -size 1200x630 xc:'#1a1b26' -gravity north -font Monocode -pointsize 256 -fill '#c0caf5' \
          -draw "text 0,10 'Aa'" \
          -gravity center \
          -font Monocode -pointsize 60 -fill '#c0caf5' \
          -draw "text 0,40 'ABCDEFGHIJKLMNOPQRSTUVWXYZ 01234'" \
          -gravity center \
          -font Monocode -pointsize 60 -fill '#c0caf5' \
          -draw "text 0,120 'abcdefghijklmnopqrstuvwxyz 56789'" \
          -gravity center \
          -font Monocode -pointsize 60 -fill '#c0caf5' \
          -draw "text 0,210 '{}[]()<>\`~!@#$%^&*?,.;:\'\"-_+=|\/'" \
          monocode-specimen.png

          cp ./monocode-specimen.png /home/runner/work/monocode/monocode/images
          cd /home/runner/work/monocode/monocode
          git add /home/runner/work/monocode/monocode/images/monocode-specimen.png

      - name: Commit and push images
        run: |
          cd /home/runner/work/monocode/monocode
          git config --local user.email "aaronmbos@gmail.com"
          git config --local user.name "Aaron Bos"

          status=$(git status --porcelain)

          if [ -z "$status" ]; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Update images"
          git push
