name: Iosevka Version Check

on:
  # At 11:00 UTC on every day-of-week from Sunday through Saturday.
  schedule:
    - cron: "0 11 * * 0-6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get Monocode's current Iosevka version
        run: |
          monocode_iosevka_version=$(cat .iosevka-version)
          monocode_version=$(cat .version)
          echo "Monocode currently using Iosevka version: ${monocode_iosevka_version}"
          echo "Current Monocode version: ${monocode_version}"
          echo "MONOCODE_IOSEVKA_VERSION=${monocode_iosevka_version}" >> $GITHUB_ENV
          echo "MONOCODE_VERSION=${monocode_version}" >> $GITHUB_ENV

      - name: Get latest Iosevka release
        run: |
          res=$(curl --request GET \
          --url https://api.github.com/repos/be5invis/Iosevka/releases/latest \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -s)
          iosevka_version=$(echo $res | jq -r '.tag_name')
          echo "Latest Iosevka release: ${iosevka_version}"
          echo "IOSEVKA_VERSION=${iosevka_version}" >> $GITHUB_ENV

      - name: Compare versions
        id: compare-versions
        run: |
          if [ "$MONOCODE_IOSEVKA_VERSION" != "$IOSEVKA_VERSION" ]; then
            echo "new_version=true" >> $GITHUB_OUTPUT
          else
            echo "Monocode is update to date with Iosevka version: $IOSEVKA_VERSION"
            exit 0
          fi

      - name: Update Version and Changelog
        if: steps.compare-versions.outputs.new_version == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Monocode is out of date with latest Iosevka release."

          git config --global user.email "aaronmbos@gmail.com"
          git config --global user.name "Aaron Bos"

          git fetch --quiet
          git checkout -b monocode-update-${IOSEVKA_VERSION} origin/main

          major_monocode_iosevka=$(echo $MONOCODE_IOSEVKA_VERSION | sed 's/v\([0-9]\+\)\..*/\1/')
          minor_monocode_iosevka=$(echo $MONOCODE_IOSEVKA_VERSION | sed 's/v[0-9]\+\.\([0-9]\+\)\..*/\1/')
          patch_monocode_iosevka=$(echo $MONOCODE_IOSEVKA_VERSION | sed 's/v[0-9]\+\.[0-9]\+\.\([0-9]\+\)/\1/')

          major_iosevka=$(echo $IOSEVKA_VERSION | sed 's/v\([0-9]\+\)\..*/\1/')
          minor_iosevka=$(echo $IOSEVKA_VERSION | sed 's/v[0-9]\+\.\([0-9]\+\)\..*/\1/')
          patch_iosevka=$(echo $IOSEVKA_VERSION | sed 's/v[0-9]\+\.[0-9]\+\.\([0-9]\+\)/\1/')

          major_diff=$(($major_iosevka - $major_monocode_iosevka))
          minor_diff=$(($minor_iosevka - $minor_monocode_iosevka))
          patch_diff=$(($patch_iosevka - $patch_monocode_iosevka))

          major_monocode=$(echo $MONOCODE_VERSION | sed 's/v\([0-9]\+\)\..*/\1/')
          minor_monocode=$(echo $MONOCODE_VERSION | sed 's/v[0-9]\+\.\([0-9]\+\)\..*/\1/')
          patch_monocode=$(echo $MONOCODE_VERSION | sed 's/v[0-9]\+\.[0-9]\+\.\([0-9]\+\)/\1/')

          if [ $major_diff -gt 0 ]; then
            updated_major=$(($major_monocode + $major_diff))
            updated_minor=0
            updated_patch=0
          elif [ $minor_diff -gt 0 ]; then
            updated_major=$major_monocode
            updated_minor=$(($minor_monocode + $minor_diff))
            patch_diff=0
          else
            updated_major=$major_monocode
            updated_minor=$minor_monocode
            updated_patch=$(($patch_monocode + $patch_diff))
          fi

          updated_version="v${updated_major}.${updated_minor}.${updated_patch}"
          iosevka_version="v${major_iosevka}.${minor_iosevka}.${patch_iosevka}"
          sed -i "s/^v[0-9]\+\.[0-9]\+\.[0-9]\+/$updated_version/" .version
          sed -i "s/^v[0-9]\+\.[0-9]\+\.[0-9]\+/$iosevka_version/" .iosevka-version

          git add .version .iosevka-version

          changelog_file="./CHANGELOG.md"
          sed -i "/^## \[Unreleased]/a\\
          \\
          ## [$updated_version] - $(date +'%Y-%m-%d')\\
          \\
          - Updating to latest version of Iosevka: ${IOSEVKA_VERSION}
          " $changelog_file

          git add CHANGELOG.md
          git commit -m "Update to Iosevka version: ${IOSEVKA_VERSION}"
          git push origin monocode-update-${IOSEVKA_VERSION}

          gh pr create --title "Update to Iosevka version: ${IOSEVKA_VERSION}" --body "Updating to latest version of Iosevka: ${IOSEVKA_VERSION}" --base main --head monocode-update-${IOSEVKA_VERSION} --repo aaronbos/monocode
