name: Iosevka Version Check

on:
  # At 11:00 UTC on every day-of-week from Sunday through Saturday.
  schedule:
    - cron: "0 11 * * 0-6"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Check Monocode's Iosevka version against latest release
        run: |
          monocode_iosevka_version=$(cat .iosevka-version)
          echo "Monocode currently using Iosevka version: ${monocode_iosevka_version}"
          res=$(curl --request GET \
          --url https://api.github.com/repos/be5invis/Iosevka/releases/latest \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          -s)
          iosevka_version=$(echo $res | jq -r '.tag_name')
          echo "Latest Iosevka release: ${iosevka_version}"
          if [ "$monocode_iosevka_version" != "$iosevka_version" ]; then
            echo "Monocode is out of date with latest Iosevka release."
            exit 1
          else
            echo "Monocode is update to date with Iosevka version: ${iosevka_version}"
            exit 0
          fi
