name: Merge

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: "16.x" # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Clone Iosevka
        run: |
          cd ..
          monocode_iosevka_version=$(cat ./monocode/.iosevka-version)
          git clone --depth 1 https://github.com/be5invis/Iosevka.git
          cd Iosevka
          git fetch --tags
          git checkout tags/${monocode_iosevka_version}

      - name: npm install, build
        run: |
          cd ../Iosevka
          cp ../monocode/private-build-plans.toml ./private-build-plans.toml
          npm install
          npm run build -- ttf::monocode

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node-app
      #     path: .
